# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "VagrantVM"
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "VagrantVM"
  config.vm.synced_folder "../services", "/home/Hotel_services", 
  type: "virtualbox", owner: "vagrant", group: "vagrant"
end
